### ISSUE TITLE
Changing a snitch's reinforcement group does not change the snitch group.

### ISSUE THREAD

**Issue by Inframission** [CivClassic/JukeAlert#31]
Creating a snitch on Bob's group then using ctr to change its group to Alice will create a block reinforced to Alice that pings Bob

**Comment by Diet-Cola** [comment]
[Courtesy of ProgrammerDan](https://github.com/CivClassic/JukeAlert/pull/36)

**Comment by wingzero54** [comment]
Fixed with #36
