### ISSUE TITLE
Disabling inactive snitches locks up server

### ISSUE THREAD

**Issue by wingzero54** [CivClassic/JukeAlert#43]
All snitches are parsed to check for inactive snitches and then deactivated on server startup. This locks up the server, and you are unable to connect to the server while it is disabling snitches. I presume this task needs to be made async?

**Comment by wingzero54** [comment]
As an example, one day it took 6 minutes to deactivate or cull 500 snitches. That is almost one second for every snitch

**Comment by Diet-Cola** [comment]
More info on this: We've ruled out that disabling/culling snitches causes the start up lag, it is loading **all** snitches into memory on startup that stalls the start up of the server.

**Comment by wingzero54** [comment]
See #52

**Comment by wingzero54** [comment]
Fixed with #58  JukeAlert was loading all snitch logs into memory, which was taking 6 minutes on server startup, keeping ram usage higher and causing every GC to take longer. All of which has improved massively since snitch logs were removed from memory
