### ISSUE TITLE
Remove player heads from /ja

### ISSUE THREAD

**Issue by wingzero54** [CivClassic/JukeAlert#47]
Would save on the massive lag spikes caused by /ja on large snitches, and resolve #29 . And really, player heads on /ja are nothing more than a neat little design addition

**Comment by wingzero54** [comment]
Alternatively some kind of batching / caching of heads to make it much smarter

**Comment by caucow** [comment]
> Alternatively some kind of batching / caching of heads to make it much smarter

Dunno exactly how the skin-getting stuff works but from discord:
- caching - not having to ask a server for a file you already have is faster
- lazy "initialization"/skin download - don't get skins for heads that wouldn't be visible on the current page of the UI
- load skins async, update the item accordingly - Basically do something similar to Swing/AWT Graphics.drawImage(..., ImageObserver) where you draw "what you have" of an image (ie use a placeholder item of some sort) then once the rest of the image (skin) is available/loaded, redraw the image (update the item).
